#!/bin/bash

install_debian()
{
    echo "NOTE: Make sure you have done apt-get update and apt-get upgrade prior to running this script."
    echo "Installing Debian/Ubuntu dependencies"
    echo "-------"

    sudo apt-get --yes --force-yes install gobjc 
    sudo apt-get --yes --force-yes install gobjc++
    sudo apt-get --yes --force-yes install clang
    sudo apt-get --yes --force-yes install libjpeg-dev 
    sudo apt-get --yes --force-yes install libtiff-dev 
    sudo apt-get --yes --force-yes install libpng-dev 
    sudo apt-get --yes --force-yes install libicns-dev
    sudo apt-get --yes --force-yes install libmagickcore-dev
    sudo apt-get --yes --force-yes install libxml2-dev 
    sudo apt-get --yes --force-yes install libxslt-dev 
    sudo apt-get --yes --force-yes install libgnutls-dev
    sudo apt-get --yes --force-yes install libffi-dev 
    sudo apt-get --yes --force-yes install libicu-dev 
    sudo apt-get --yes --force-yes install libcairo2-dev
    sudo apt-get --yes --force-yes install libxft-dev
    sudo apt-get --yes --force-yes install libavahi-client-dev
    sudo apt-get --yes --force-yes install flite-dev
    sudo apt-get --yes --force-yes install libxt-dev
    sudo apt-get --yes --force-yes install libportaudio-dev
    sudo apt-get --yes --force-yes install wmaker
    sudo apt-get --yes --force-yes install portaudio19-dev
    sudo apt-get --yes --force-yes install make
    sudo apt-get --yes --force-yes install cmake
    sudo apt-get --yes --force-yes install gnutls-dev
    sudo apt-get --yes --force-yes install libblocksruntime-dev
    sudo apt-get --yes --force-yes install pocketsphinx
    sudo apt-get --yes --force-yes install pocketsphinx-en-us
    sudo apt-get --yes --force-yes install libpocketsphinx-dev
    sudo apt-get --yes --force-yes install libsphinxbase-dev
    sudo apt-get --yes --force-yes install sphinxbase-utils
    sudo apt-get --yes --force-yes install sphinxtrain
    sudo apt-get --yes --force-yes install libssl-dev
    sudo apt-get --yes --force-yes install freeglut3-dev

# CJEC, 14-Mar-22: Install additional dependencies for Ubuntu 20.04 build with CLANG
#					defined in https://github.com/plaurent/gnustep-build.git /ubuntu-20.04-clang-10.0-runtime-2.0/GNUstep-buildon-ubuntu2004.sh
	sudo apt -y install build-essential wget git subversion \
		libgnutls28-dev libkqueue-dev libpthread-workqueue-dev autoconf libtool \
		libcairo-dev libx11-dev libxrandr-dev \
		curl lld

# CJEC, 26-Sep-22: Install GnuTLS runtime required for TLS support in GNUstep Foundation.
#			make check fails for libs-base without this.
#			https://help.ubuntu.com/community/GnuTLS
	sudo apt-get --yes --force-yes install gnutls-bin

# CJEC, 3-Oct-22: Install required tools to build GNUstep documentation
#			make install cannot find makeinfo, latex
	sudo apt-get --yes --force-yes install texinfo
	sudo apt-get --yes --force-yes install texlive-latex-recommended

# tofts, 26-Apr-23: Install net-tools dependency to provide the ifconfig command for AmiShare.
	sudo apt-get --yes --force-yes install net-tools

# CJEC, 22-NOv-23: Install additional dependencies required by AmiShare
	sudo apt -y install sqlite3 libsqlite3-dev
	sudo apt -y install libbluetooth-dev
	sudo apt -y install libbsd-dev
	sudo apt -y install libfuse-dev

    echo "-------"
    echo "Done..."
}

install_redhat()
{
    echo "NOTE: Make sure you have done apt-get update and apt-get upgrade prior to running this script."
    echo "Installing RedHat/CentOS/etc dependencies"
    echo "-------"

    sudo yum -y install gcc 
    sudo yum -y install gcc-objc
    sudo yum -y install clang
    sudo yum -y install libjpeg-turbo-devel 
    sudo yum -y install libtiff-devel 
    sudo yum -y install libpng-devel
    sudo yum -y install libicns-devel
    sudo yum -y install ImageMagick-devel
    sudo yum -y install libxml2-devel
    sudo yum -y install libxslt-devel
    sudo yum -y install gnutls-devel
    sudo yum -y install libffi-devel
    sudo yum -y install libicu-devel
    sudo yum -y install cairo-devel
    sudo yum -y install libXft-devel
    sudo yum -y install avahi-devel
    sudo yum -y install flite-devel
    sudo yum -y install libXt-devel
#    sudo yum -y install libportaudio-devel
#    sudo yum -y install wmaker
#    sudo yum -y install portaudio19-dev
    sudo yum -y install make
    sudo yum -y install cmake
#    sudo yum -y install libblocksruntime-dev
#    sudo yum -y install pocketsphinx
#    sudo yum -y install pocketsphinx-en-us
#    sudo yum -y install libpocketsphinx-dev
#    sudo yum -y install libsphinxbase-dev
#    sudo yum -y install sphinxbase-utils
#    sudo yum -y install sphinxtrain
    sudo yum -y install openssl-devel
    sudo yum -y install gnutls-devel

    echo "-------"
    echo "Done..."
}

get_system()
{
    if [ -e /etc/os-release ]; then
        . /etc/os-release
    fi
}

get_system
echo "You are using ${ID}"

case ${ID} in
    debian)
        install_debian
        ;;
    ubuntu)
        install_debian
        ;;
    raspbian)
        install_debian
        ;;
    redhat)
        install_redhat
        ;;
    centos)
        install_redhat
        ;;
    suse)
        install_redhat
        ;;
    fedora)
        install_redhat
        ;;
    *)
        echo "Please report this to bugs-gnustep@gnu.org."
        echo "Your linux os ${ID} is currently unsupported."
        exit 255
        ;;
esac 
exit 0
