#!/bin/bash

install_android()
{
    echo "NOTE: Make sure you have done apt-get update and apt-get upgrade prior to running this script."
    echo "Installing Android dependencies"
    echo "-------"

	pkg install root-repo		# For libfuse2
	pkg install x11-repo		# Not strictly necessary for the Foundation/base libraries, but probably essential for full GNUstep

#    pkg install gobjc			# Don't need GCC as well as clang
#    pkg install gobjc++
    pkg install clang
    pkg install binutils-gold	# Android package for ld.gold
    pkg install binutils		# Android package for nm and other essential tools
#    pkg install libdispatch	# Android has this package for libdispatch (Blocks support) but we build it ourselves in ./compile-all
#    pkg install libjpeg-dev 
    pkg install libjpeg-turbo	# Try this on Android
    pkg install libtiff			# Changed from -dev
    pkg install libpng			# Changed from -dev 
    pkg install libicns-dev
    pkg install libmagickcore-dev
    pkg install libxml2			# Changed from -dev
    pkg install libxslt			# Changed from -dev
    pkg install libgnutls		# Changed from -dev
    pkg install libffi			# Changed from -dev
    pkg install libicu 			# Changed from -dev 
#    pkg install libcairo2-dev	# Does not exist on Android.
    pkg install libcairo		# Try this on Android
    pkg install libxft			# Changed from -dev
#    pkg install libavahi-client-dev	# Does not exist on Android.
    pkg install avahi			# Try this on Android
#    pkg install flite-dev 		# Does not exist on Android.
    pkg install libxt 			# Changed from -dev
#    pkg install libportaudio-dev	# Does not exist on Android.
    pkg install wmaker
    pkg install portaudio 		# Changed from portaudio19-dev
    pkg install make
    pkg install cmake
    pkg install gnutls 			# Changed from -dev
    pkg install libblocksruntime 	# Changed from -dev
#    pkg install pocketsphinx	# Does not exist on Android
#    pkg install pocketsphinx-en-us	# Does not exist on Android
#    pkg install libpocketsphinx-dev	# Does not exist on Android
#    pkg install libsphinxbase-dev	# Does not exist on Android
#    pkg install sphinxbase-utils	# Does not exist on Android
#    pkg install sphinxtrain	# Does not exist on Android
#    pkg install libssl-dev		# Doesn't exist, but there are openssl variants?
    pkg install openssl openssl-tool	# Try this on Android
    pkg install openssl-1.1 openssl1.1-tool	# Also install OpenSSL 1.1 on Android
    pkg install freeglut		# Changed from freeglut3-dev

# CJEC, 14-Mar-22: Install additional dependencies for Ubuntu 20.04 build with CLANG
    #				defined in https://github.com/plaurent/gnustep-build.git /ubuntu-20.04-clang-10.0-runtime-2.0/GNUstep-buildon-ubuntu2004.sh
# SNT, 9-Jan-23: From this list, we have:
# 					build-essential, wget, git, and subversion all work.
# 					libgnutls28-dev -> libgnutls
# 					libkqueue-dev and libpthread-workqueue-dev don't exist.
# 					autoconf and libtool work.
# 					libcairo-dev -> libcairo
# 					libx11-dev -> libx11
# 					libxrandr-dev -> libxrandr
# 					And finally, curl works.
	pkg install build-essential wget git subversion
	pkg	install libgnutls 		# libkqueue-dev libpthread-workqueue-dev
	pkg install autoconf libtool
	pkg install libcairo libx11 libxrandr
	pkg install curl
	pkg install lld
# CJEC, 26-Sep-22: Install GnuTLS runtime required for TLS support in GNUstep Foundation.
#			make check fails for libs-base without this.
#			https://help.ubuntu.com/community/GnuTLS
#	pkg install gnutls-bin
	pkg install gnutls			# Try this on Android

# CJEC, 3-Oct-22: Install required tools to build GNUstep documentation
#			make install cannot find makeinfo, latex
	pkg install texinfo
#	pkg install texlive-latex-recommended

# CJEC, 12-Jan-23: Add essential Android/Termux libraries for POSIX system calls etc.
	pkg install libandroid-posix-semaphore
	pkg install libandroid-posix-shmem
	pkg install libandroid-sysv-semaphore
	pkg install libandroid-execinfo

# tofts, 13-Jan-23: Install libdispatch.
	pkg install libdispatch
	
# CJEC 11-Jan-23: Add components from additional repositories 
	pkg install libfuse2 	# In the root-repo repository
		
# CJEC, 9-Jan-23: Finally check all packages are up to date
	pkg upgrade

# tofts, 13-Jan-23: Create directory with sym-links.
	rm -rf ~/../usr/system_override_libs
	mkdir ~/../usr/system_override_libs
	ln -s /system/lib64/libEGL.so ~/../usr/system_override_libs/libEGL.so
	ln -s /system/lib64/libGLESv1_CM.so ~/../usr/system_override_libs/libGLESv1_CM.so
	ln -s /system/lib64/libheif.so ~/../usr/system_override_libs/libheif.so
	ln -s /system/lib64/libcrypto.so ~/../usr/system_override_libs/libcrypto.so
	ln -s /system/lib64/liblzma.so ~/../usr/system_override_libs/liblzma.so
	
    echo "-------"
    echo "Done..."
}

install_android
